import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'

describe('basic demo Entry integration route', () => {
  it('renders and previews through the public Entry path rather than the bare syntax-tree view', () => {
    const app = readFileSync(new URL('../../examples/basic-demo/src/App.tsx', import.meta.url), 'utf8')
    const main = readFileSync(new URL('../../examples/basic-demo/src/main.tsx', import.meta.url), 'utf8')
    const presets = readFileSync(new URL('../../examples/basic-demo/src/demoPresets.ts', import.meta.url), 'utf8')
    const readme = readFileSync(new URL('../../README.md', import.meta.url), 'utf8')
    const readmeZh = readFileSync(new URL('../../README(ZH).md', import.meta.url), 'utf8')
    const pkg = JSON.parse(readFileSync(new URL('../../examples/basic-demo/package.json', import.meta.url), 'utf8')) as { dependencies: Record<string, string>; scripts: Record<string, string> }
    const prepareScript = readFileSync(new URL('../../examples/basic-demo/scripts/prepare-local-package.mjs', import.meta.url), 'utf8')
    expect(app).toContain('EntryPreviewProvider')
    expect(app).toContain('EntrySurface')
    expect(app).toContain('EntryDataDriver')
    expect(app).toContain('createSvgTemplateRenderer')
    expect(app).toContain('SvgTemplateAssetRegistry')
    expect(presets).toContain("block_template_name: 'svg_template'")
    expect(presets).toContain('formula_embed')
    expect(app).toContain("renderers: { svg_template: svgRenderer }")
    expect(app).toContain('DEMO_PRESETS.map')
    expect(app).toContain('aria-pressed={preset.id === activePresetId}')
    expect(app).not.toContain('SnlSyntaxTreeView')
    expect(app).not.toContain('prefers-color-scheme: dark')
    expect(app).not.toContain("color_scheme: 'dark'")
    expect(app.match(/color_scheme: 'light'/g)).toHaveLength(2)
    expect(main).toContain('@sjtu-ai4math/snl-basics/style.css')
    expect(main).toContain('@sjtu-ai4math/snl-basics/entry/style.css')
    expect(pkg.dependencies['@sjtu-ai4math/snl-basics']).toBe('file:../..')
    expect(pkg.scripts.postinstall).toBe('node scripts/prepare-local-package.mjs')
    expect(pkg.scripts.predev).toBe('node scripts/prepare-local-package.mjs')
    expect(pkg.scripts.prebuild).toBe('node scripts/prepare-local-package.mjs')
    expect(prepareScript).toContain("process.platform === 'win32'")
    expect(prepareScript).toContain("['run', 'build:lib']")
    expect(readme).toContain('links the repository root through `file:../..`')
    expect(readmeZh).toContain('通过 `file:../..` 链接仓库根包')
    expect(readme).not.toContain('from the packed tarball')
    expect(readmeZh).not.toContain('从打包出的 tarball 安装')
    expect(readme).not.toContain('300')
    expect(readmeZh).not.toContain('300')
  })
})
